GET http://localhost:8080/api/v1/books

### 
# will return second page
GET http://localhost:8080/api/v1/books?cursor=10

### 
# will return error because of invalid cursor
GET http://localhost:8080/api/v1/books?cursor=abc
###

# will return error because of invalid book id
GET http://localhost:8080/api/v1/books/0

###
# returns a book
GET http://localhost:8080/api/v1/books/1

###
# fails with 500 status code and the error message is not exposed
GET http://localhost:8080/api/v1/books/1?fail=true

### 
# will fail because of the missing required field
POST http://localhost:8080/api/v1/books
Content-Type: application/json
Authorization: Bearer admin_token_12345

{
    "title": "The Great Gatsby",
    "author": "F. Scott Fitzgerald"
}

###
# will fail because of json parsing error
POST http://localhost:8080/api/v1/books
Content-Type: application/json
Authorization: Bearer admin_token_12345

{
    "title": "The Great Gatsby",
    "author": "F. Scott Fitzgerald",
}

###
# will fail with 401 status code because of missing authorization header
POST http://localhost:8080/api/v1/books
Content-Type: application/json

{
    "title": "The Great Gatsby",
    "author": "F. Scott Fitzgerald",
    "description": "A novel about the American Dream"
}

###
# will fail with 401 status code because of invalid token
POST http://localhost:8080/api/v1/books
Content-Type: application/json
Authorization: Bearer invalid_token

{
    "title": "The Great Gatsby",
    "author": "F. Scott Fitzgerald",
    "description": "A novel about the American Dream"
}

###
# will create a new book
POST http://localhost:8080/api/v1/books
Content-Type: application/json
Authorization: Bearer admin_token_12345

{
    "title": "The Great Gatsby",
    "author": "F. Scott Fitzgerald",
    "description": "A novel about the American Dream"
}

###
# will fail with 403 status code because of moderator role
POST http://localhost:8080/api/v1/books
Content-Type: application/json
Authorization: Bearer moderator_token_12345

{
    "title": "The Great Gatsby",
    "author": "F. Scott Fitzgerald",
    "description": "A novel about the American Dream"
}

###
# will fail with 409 when called second time
POST http://localhost:8080/api/v1/books/2/favorite
Content-Type: application/json
Authorization: Bearer user_token_12345

###
# will return favorite books along with books list
GET http://localhost:8080/api/v1/books
Authorization: Bearer user_token_12345